### ISSUE TITLE
input vs. arguments explainer in Lesson 2

### ISSUE THREAD

**Issue by ldliao** [dlab-berkeley/R-Fundamentals#28]
line 71-75

1.  **input** - the object that the function is operating on.
2.  **arguments** - modifications we make to the function (the first argument is usually the input).

this explainer may not be needed since they are essentially the same thing

**Comment by heroashman** [comment]
I think it's helpful to have both to draw attention to the fact that there are default arguments but rarely default inputs and so mainly we need an input but don't need arguments unless we're modifying the function

**Comment by ldliao** [comment]
can you provide an example on what you mean? also looping in @pssachdeva who prompted this comment

**Comment by pssachdeva** [comment]
my main point is that the distinction here is confusing. every input to a function has a name as per the function signature - those are the arguments. sometimes arguments have default parameters, but whether they do or not, they're all essentially inputs to the function. there's not really a distinction between inputs and arguments, the only distinction is when there is a default value which effectively makes the input/argument optional for running the function

i think making the point of default argument vs not is important in this section, but delineating between inputs and arguments (and even parameters), when they're generally used synonymously might be confusing to explain

**Comment by heroashman** [comment]
That makes sense, thanks for the explanation both! I have editted the functions section to be as follows. Let me know if that looks good and I'll push the changes. 

Functions are commands that take an **input** and return some **output**. They are identified by the trailing brackets. Inside the brackets go inputs (also called **arguments**). Each input takes a value that we provide when calling the function. 

To know which inputs go into a function, we look at the documentation. To call the documentation for a function type `?` then the function name. 

```{r}
# look at documentation for length()
?length

```

Under *Arguments* we see there is one input for `length()`: `x`. That means that we always need to supply `length()` with a value for x. In our case, we will input a vector. 

```{r}
# supply pop_mexico to the input x
length(x = pop_mexico)

# we don't need to specify "x = " each time bc it is the first (and in this case, only) input
length(pop_mexico)

```

Some functions have **default** arguments, which means that we don't need to supply a value to those inputs/arguments because there are default values supplied by R. For example, the function `read.csv()`, which we saw in Part 1's demo, has a default value of `TRUE` for the argument `header`. We can look up what that means in the documentation. 

```{r}
# look up header under arguments 
?read.csv

# we only need to supply a value for the argument file = and we can leave the rest as the default 
read.csv(file = "../data/gapminder.csv")

```
